# Generated by Django 4.1.1 on 2022-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_descrip',
        ),
        migrations.AddField(
            model_name='product',
            name='p_des',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(default='category/vid.jpg', upload_to='category'),
        ),
    ]
