# Generated by Django 4.1.1 on 2022-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_product_p_descrip_product_p_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_des',
            field=models.TextField(),
        ),
    ]
