# Generated by Django 4.1.1 on 2022-10-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_p_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(default='category/vid2.mp4', upload_to='category'),
        ),
    ]
