# Generated by Django 4.1.1 on 2022-11-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_address_shipping_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='billing_address',
            field=models.CharField(max_length=250),
        ),
    ]
